version: '2.1'

services:

  swift-runtime:
    image: cscix65g/swift-runtime:arm64-latest

  lldb-server:
    image: cscix65g/lldb-server:arm64-latest
    network_mode: host
    ports:
      - 8080:8080
      - 9293:9293
    volumes_from:
      - swift-runtime
    volumes:
      - /tmp:/debug
